name: Deploy Frontend
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t drecoak/docker-react .
      - name: Run NPM Test
        run: docker run -e CI=true drecoak/docker-react npm run test
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: drecoak-docker-react
          environment_name: Drecoakdockerreact-env
          existing_bucket_name: elasticbeanstalk-us-east-2-716983815128
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
